backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "links"
    label: "Links"
    folder: "content"
    create: false
    files:
      - label: "Site Links"
        name: "site_links"
        file: "content/links.json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "Profile Image", name: "profile_image", widget: "image" }
          - label: "Buttons"
            name: "buttons"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

  - name: "faqs"
    label: "FAQs"
    folder: "content/faqs"
    create: true
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Question", name: "title", widget: "string" }
      - { label: "Answer", name: "body", widget: "text" }

